package com.assignment.contactsservice.event;

import java.io.Serializable;

/**
 * Represents the event payload published after a contact is successfully
 * created. This class defines the data contract for the message broker. The
 * payload structure is: { "id": integer, "name": string }.
 * 
 * 
 * Required marker interface for Kafka/Pulsar serialization
 */
public class ContactCreatedEvent implements Serializable {

	private Long id;
	private String name;

	// Default Constructor (required for serialization/deserialization)
	public ContactCreatedEvent() {
	}

	/**
	 * Parameterized constructor to create an event instance upon successful contact
	 * creation.
	 * 
	 * @param id   The ID of the newly created contact, typically generated by the
	 *             database.
	 * @param name The name of the new contact.
	 */
	public ContactCreatedEvent(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Provides a string representation of the event payload for logging and
	 * debugging purposes.
	 * 
	 * @return A string detailing the event's fields.
	 */

	@Override
	public String toString() {
		return "ContactCreatedEvent{" + "id=" + id + ", name='" + name + '\'' + '}';
	}

}
